#!/usr/bin/env python3
"""
Bar plot of mean % correct layerheads per protein (domain),
using the CSV generated by your R script.

Input CSV expected: DOMAIN_SUMMARY_WITH_ASTRAL.csv
Columns expected: Domain, pct_correct, correct, wrong, astral_status
"""

from __future__ import annotations

import os
import argparse
import pandas as pd
import matplotlib.pyplot as plt


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--csv",
        default="/home/rohan/PLM-Phylo/Plots/DOMAIN_SUMMARY_WITH_ASTRAL.csv",
        help="Path to DOMAIN_SUMMARY_WITH_ASTRAL.csv",
    )
    parser.add_argument(
        "--outdir",
        default="/home/rohan/PLM-Phylo/Plots/",
        help="Output directory for plot + cleaned CSV",
    )
    parser.add_argument(
        "--sort",
        choices=["pc", "name", "none"],
        default="pc",
        help="Sort bars by percent-correct (pc), by domain name (name), or not at all (none).",
    )
    parser.add_argument(
        "--annotate_values",
        action="store_true",
        help="If set, write the % value above each bar (can get crowded).",
    )

    args = parser.parse_args()
    os.makedirs(args.outdir, exist_ok=True)

    # ---- Global font sizes ----
    plt.rcParams.update({
        "font.size": 16,
        "axes.labelsize": 16,
        "xtick.labelsize": 12,
        "ytick.labelsize": 16,
    })

    df = pd.read_csv(args.csv)

    # Coerce pct_correct to numeric; drop NaNs
    df["pct_correct"] = pd.to_numeric(df["pct_correct"], errors="coerce")
    df_clean = df.dropna(subset=["pct_correct"]).copy()

    if df_clean.empty:
        raise SystemExit("No non-NA pct_correct values found in the CSV.")

    # Sorting
    if args.sort == "pc":
        df_clean = df_clean.sort_values("pct_correct", ascending=False)
    elif args.sort == "name":
        df_clean = df_clean.sort_values("Domain", ascending=True)

    # Save cleaned/sorted table
    out_csv = os.path.join(
        args.outdir, "PC_MEAN_PER_PROTEIN_FROM_DOMAIN_SUMMARY.csv"
    )
    df_clean.to_csv(out_csv, index=False)

    # ---- Plot ----
    x = df_clean["Domain"].astype(str).tolist()
    y = df_clean["pct_correct"].astype(float).tolist()

    fig, ax = plt.subplots(figsize=(10, 5))

    ax.bar(x, y, color="orange", zorder=3)
    ax.set_ylim(0, 100)
    ax.set_ylabel("Percentage of correct SAM trees")
    #ax.set_xlabel("Protein")

    ax.set_xticks(range(len(x)))
    ax.set_xticklabels(x, rotation=90)

    # Grid BEHIND bars
    ax.set_axisbelow(True)
    ax.grid(axis="y", alpha=0.5)

    # Optional annotations
    if args.annotate_values:
        for i, val in enumerate(y):
            ax.text(
                i,
                val + 1.0,
                f"{val:.1f}",
                ha="center",
                va="bottom",
                fontsize=16,
            )

    plt.tight_layout()

    out_png = os.path.join(args.outdir, "PC_BAR_MEAN_PER_PROTEIN.png")
    plt.savefig(out_png, dpi=300, facecolor="white")
    plt.show()
    plt.close()

    print(f"Read:   {args.csv}")
    print(f"Wrote:  {out_csv}")
    print(f"Wrote:  {out_png}")


if __name__ == "__main__":
    main()
